apiVersion: batch/v1
kind: CronJob
metadata:
  name: behave-ui-test
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: behave-container
              image: my-behave-image:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: BASE_URL
                  value: "SDAIA"
                - name: DEMO_FAREWELL
                  value: "Such a sweet sorrow"

              command: ["behave"]
          restartPolicy: Never
