apiVersion: batch/v1
kind: CronJob
metadata:
  name: behave-ui-test
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: behave-container
              image: my-behave-image:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: BASE_URL
                  value: "https://sdaia.gov.sa/en/"
                - name: MAIN_PAGE
                  value: "default.aspx#"
                - name: SEARCH_RESULT_PAGE
                  value: "Search/Pages/results.aspx?"
              command: ["behave"]
          restartPolicy: Never
